services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - monitor-net
    depends_on:
      - flask-app

  docker-agent:
    image: jenkins/inbound-agent
    container_name: docker-agent
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=fb3ea9473f3e5c18f4150ee58b598de8f89cf95530793b2f9b765133b2d969ef
      - JENKINS_AGENT_NAME=docker-agent
    networks:
      - monitor-net

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "8080:8080"  # Mantido como está, já que você já está utilizando essa porta
    networks:
      - monitor-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitor-net
    deploy:
      mode: global

  nginx:
    image: nginx:latest
    container_name: meu-nginx
    ports:
      - "8081:80"
    volumes:
      - /home/bruno/devops-treino/devops-treino/nginx/flask_app.conf:/etc/nginx/conf.d/flask_app.conf
    networks:
      - monitor-net
    depends_on:
      - flask-app

networks:
  monitor-net:
    driver: bridge

volumes:
  grafana_data:
  jenkins_home:
