version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - monitor-net
    depends_on:
      - flask-app

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask-app
    ports:
      - "8080:8080"
    networks:
      - monitor-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - /home/bruno/devops-treino/devops-treino/nginx/flask_app.conf:/etc/nginx/conf.d/flask_app.conf
    networks:
      - monitor-net
    depends_on:
      - flask-app

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/bruno/devops-treino/devops-treino/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net
    depends_on:
      - flask-app
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitor-net
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitor-net

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile.jenkins.agent
    container_name: jenkins-agent
    environment:
      - JENKINS_SECRET=fb3ea9473f3e5c18f4150ee58b598de8f89cf95530793b2f9b765133b2d969ef
    networks:
      - monitor-net
    restart: always

networks:
  monitor-net:
    driver: bridge

volumes:
  grafana_data:
  jenkins_home:
