global:
  scrape_interval: 15s  # Intervalo para coleta das métricas

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['localhost:8080']  # Endereço da sua aplicação Flask

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']  # Endereço do Node Exporter
