global:
  scrape_interval: 15s  # Intervalo para coleta das métricas

scrape_configs:
  - job_name: 'flask-app'
    scrape_interval: 15s  # Intervalo de coleta específico para o Flask
    static_configs:
      - targets: ['flask-app:8080']  # Nome do container Flask

  - job_name: 'node-exporter'
    scrape_interval: 15s  # Intervalo de coleta específico para o Node Exporter
    static_configs:
      - targets: ['node-exporter:9100']  # Nome do container Node Exporter