name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_cd_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Confirm Flask installation
      run: pip show flask

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run tests
      run: pytest --maxfail=1 --disable-warnings -v

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.flask  # Especifica o nome do Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest,${{ secrets.DOCKER_USERNAME }}/my-flask-app:${{ github.sha }}

    - name: Deploy with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Notify Slack
      if: success()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        text: "Deploy bem-sucedido: ${{ github.sha }}"

    - name: Clean up Docker
      if: always()
      run: docker-compose -f docker-compose.yml down
