name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Defina uma versão específica do Python

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt  # Certifique-se de que pytest está listado aqui

    - name: Check if tests exist
      run: |
        if ! ls tests/*.py 1> /dev/null 2>&1; then
          echo "No tests found!"; exit 1;
        fi

    - name: Run tests
      run: pytest --maxfail=1 --disable-warnings -v  # Executar pytest com opções para maior robustez

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
